// constants/banks.ts
export const NIGERIAN_BANKS = [
  "Access Bank",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Keystone Bank",
  "Polaris Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank Nigeria",
  "Sterling Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
  "Jaiz Bank",
  "Titan Trust Bank",
  "Globus Bank",
  "Parallex Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "SunTrust Bank Nigeria",
  "Lotus Bank",
  "TAJBank",
  "Mutual Trust Microfinance Bank",
  "Rephidim Microfinance Bank",
  "Shepherd Trust Microfinance Bank",
  "Accion Microfinance Bank",
  "Peace Microfinance Bank",
  "Infinity Microfinance Bank",
  "Fina Trust Microfinance Bank",
  "Microcred Microfinance Bank",
  "Lavender Microfinance Bank",
  "Full Range Microfinance Bank",
  "Addosser Microfinance Bank",
  "Sparkle Microfinance Bank",
  "Kuda Microfinance Bank",
  "VFD Microfinance Bank",
  "Mint Finexis Microfinance Bank",
  "Rahama Microfinance Bank",
  "Trustfund Microfinance Bank",
  "Fortis Microfinance Bank",
  "Greenwich Microfinance Bank",
  "Page Microfinance Bank",
  "Seedvest Microfinance Bank",
  "Yes Microfinance Bank",
];
